#pragma once

#include "rl_blaspp.hh"
#include "rl_lapackpp.hh"

#include <RandBLAS.hh>
#include <iostream>
#include <cmath>
#include <algorithm>
#include <vector>
#include <cstdint>
#include <sstream>
#include <fstream>
#include <unordered_map>

namespace RandLAPACK::gen {

/// An enumeration describing various matrix types by name.
/// Each matrix type can be generated bt mat_gen() utility function.
/// This list is expected to grow.
enum mat_type {
    polynomial, 
    exponential, 
    gaussian, 
    step, 
    spiked, 
    adverserial, 
    bad_cholqr,
    kahan,
    custom_input};

/// A struct containing info about a given matrix to be generated by mat_gen().
/// Requires only the size and type of a matrix by default, but can have other optional parameters.
template <typename T>
struct mat_gen_info {
    int64_t rows;
    int64_t cols;
    int64_t rank = std::min(rows, cols);
    mat_type m_type;
    T cond_num = 1.0;
    T scaling = 1.0;
    T exponent = 1.0;
    bool diag = false;
    bool check_true_rank = false;
    T theta = 1.0;
    T perturb = 1.0;
    char* filename;
    int workspace_query_mod;
    T frac_spectrum_one = 0.1;

    mat_gen_info(int64_t& m, int64_t& n, mat_type t) {
        rows = m;
        cols = n;
        m_type = t;
        rank = n; // < default
    }
};

/// Given singular values, generates left and right singular vectors and combines all into a single matrix.
/// Note: Printed matrix A may have different rank from actual generated matrix A
template <typename T, typename RNG>
void gen_singvec(
    int64_t m,
    int64_t n,
    T* A,
    int64_t k,
    T* S,
    RandBLAS::RNGState<RNG> &state
) {
    std::fill(&A[0], &A[m * n], 0.0);
    T* U   = new T[m * k]();
    T* V   = new T[n * k]();
    T* tau = new T[k]();

    RandBLAS::DenseDist DU(m, k);
    RandBLAS::DenseDist DV(n, k);
    state = RandBLAS::fill_dense(DU, U, state);
    state = RandBLAS::fill_dense(DV, V, state);

    blas::copy(k, S, k + 1, A, m + 1);

    lapack::geqrf(m, k, U, m, tau);
    lapack::ormqr(Side::Left, Op::NoTrans, m, n, k, U, m, tau, A, m);

    lapack::geqrf(n, k, V, n, tau);
    lapack::ormqr(Side::Right, Op::Trans, m, n, k, V, n, tau, A, m);

    delete[] U;
    delete[] V;
    delete[] tau;
}

/// Generates a matrix with polynomially-decaying spectrum of the following form:
/// s_i = a(i + b)^p, where p is the user-defined exponent constant, a and b are computed
/// using p and the user-defined condition number parameter and the first 10 percent of the 
/// singular values are equal to one.
/// User can optionally choose for the matrix to be diagonal.
/// The output matrix has k singular values. 
template <typename T, typename RNG>
void gen_poly_mat(
    int64_t &m,
    int64_t &n,
    T* A,
    int64_t k,
    T frac_spectrum_one,
    T cond,
    T p,
    bool diagon,
    RandBLAS::RNGState<RNG> &state
) {

    // Predeclare to all nonzero constants, start decay where needed
    T* s = new T[k]();
    T* S = new T[k * k]();

    // The first 10% of the singular values will be equal to one
    int offset = (int) floor(k * frac_spectrum_one);
    T first_entry = 1.0;
    T last_entry = first_entry / cond;
    T neg_invp = -((T)1.0)/p;
    T a = std::pow((std::pow(last_entry, neg_invp) - std::pow(first_entry, neg_invp)) / (k - offset), p);
    T b = std::pow(a * first_entry, neg_invp) - offset;
    // apply lambda function to every entry of s
    std::fill(s, s + offset, 1.0);
    for (int i = offset; i < k; ++i) {
        s[i] = 1 / (a * std::pow(offset + b, p));
        ++offset;
    }

    // form a diagonal S
    RandLAPACK::util::diag(k, k, s, k, S);

    if (diagon) {
        lapack::lacpy(MatrixType::General, k, k, S, k, A, k);
    } else {
        RandLAPACK::gen::gen_singvec(m, n, A, k, S, state);
    }

    delete[] s;
    delete[] S;
}

/// Generates a matrix with exponentially-decaying spectrum of the following form:
/// s_i = e^((i + 1) * -t), where t is computed using the user-defined cndition number parameter;
/// the first 10 percent of the singular values are equal to one.
/// User can optionally choose for the matrix to be diagonal.
/// The output matrix has k singular values. 
template <typename T, typename RNG>
void gen_exp_mat(
    int64_t &m,
    int64_t &n,
    T* A,
    int64_t k,
    T cond,
    bool diagon,
    RandBLAS::RNGState<RNG> &state
) {
    T* s = new T[k]();
    T* S = new T[k * k]();

    // The first 10% of the singular values will be =1
    int offset = (int) floor(k * 0.1);

    T t = -log(1 / cond) / (k - offset);

    T cnt = 0.0;
    // apply lambda function to every entry of s
    // Please make sure that the first singular value is always 1
    std::fill(s, s + offset, 1.0);
    for (int i = offset; i < k; ++i) {
        s[i] = (std::exp(++cnt * -t));
        ++offset;
    }

    // form a diagonal S
    RandLAPACK::util::diag(k, k, s, k, S);
    if (diagon) {
        lapack::lacpy(MatrixType::General, k, k, S, k, A, k);
    } else {
        RandLAPACK::gen::gen_singvec(m, n, A, k, S, state);
    }

    delete[] s;
    delete[] S;
}

/// Generates matrix with a staircase spectrum with 4 steps.
/// Output matrix is m by n of rank k.
/// Boolean parameter 'diag' signifies whether the matrix is to be
/// generated as diagonal.
/// Parameter 'cond' signfies the condition number of a generated matrix.
template <typename T, typename RNG>
void gen_step_mat(
    int64_t &m,
    int64_t &n,
    T* A,
    int64_t k,
    T cond,
    bool diagon,
    RandBLAS::RNGState<RNG> &state
) {

    // Predeclare to all nonzero constants, start decay where needed
    T* s = new T[k]();
    T* S = new T[k * k]();

    // We will have 4 steps controlled by the condition number size and starting with 1
    int offset = (int) (k / 4);

    std::fill(s, s + offset, 1.0);
    std::fill(s + offset, s + 2 * offset, 8.0 / cond);
    std::fill(s + 2 * offset, s + 3 * offset, 4.0 / cond);
    std::fill(s + 3 * offset, s + k, 1.0 / cond);

    // form a diagonal S
    RandLAPACK::util::diag(k, k, s, k, S);

    if (diagon) {
        lapack::lacpy(MatrixType::General, k, k, S, k, A, k);
    } else {
        RandLAPACK::gen::gen_singvec(m, n, A, k, S, state);
    }

    delete[] s;
    delete[] S;
}

/// Generates a matrix with high coherence between the left singular vectors.
/// Output matrix is m by n, full-rank.
/// Such matrix would be difficult to sketch.
/// Right singular vectors are sampled uniformly at random.
template <typename T, typename RNG>
void gen_spiked_mat(
    int64_t &m,
    int64_t &n,
    T* A,
    T spike_scale,
    RandBLAS::RNGState<RNG> &state
) {

    int64_t num_rows_sampled = n / 2;

    /// sample from [m] without replacement. Get the row indices for a tall LASO with a single column.
    int64_t* rows   = new int64_t[num_rows_sampled]();
    state = RandBLAS::repeated_fisher_yates(num_rows_sampled, m, 1, rows, state);

    T* V   = new T[n * n]();
    T* tau = new T[n]();

    RandBLAS::DenseDist DV(n, n);
    state = RandBLAS::fill_dense(DV, V, state);

    lapack::geqrf(n, n, V, n, tau);
    lapack::ungqr(n, n, n, V, n, tau);

    // Fill A with stacked copies of V
    int64_t size = 0;
    int i, j;

    while(size < m){
        lapack::lacpy(MatrixType::General, std::min(n, m - size), n, V, n, &A[size], m);
        size += std::min(n, m - size);
    }

    for (i = 0; i < n; ++ i) {
        for (j = 0; j < num_rows_sampled; ++j) {
            A[m * i + rows[j]] *= spike_scale;
        }
        j = 0;
    }

    delete[] rows;
    delete[] V;
    delete[] tau;
}

/// Generates a numerically rank-deficient matrix.
/// Added per Oleg's suggestion.
/// Output matrix is m by n of some rank k < n.
/// Generates a matrix of the form A = UV, where
/// U is an m by n Gaussian matrix whose first row was scaled by a factor sigma, and that then 
/// was orthonormalized with a Householder QR. 
/// The matrix V is the upper triangular part of an n × n 
/// orthonormalized Gaussian matrix with modified diagonal entries to diag(V) *= [1, 10^-15, . . . , 10^-15, 10^-15].
template <typename T, typename RNG>
void gen_oleg_adversarial_mat(
    int64_t &m,
    int64_t &n,
    T* A,
    T sigma,
    RandBLAS::RNGState<RNG> &state
) {

    T scaling_factor_U = sigma;
    T scaling_factor_V = 10e-3;

    T* U    = new T[m * n]();
    T* V    = new T[n * n]();
    T* tau1 = new T[n]();
    T* tau2 = new T[n]();

    RandBLAS::DenseDist DU(m, n);
    state = RandBLAS::fill_dense(DU, U, state);

    RandBLAS::DenseDist DV(n, n);
    state = RandBLAS::fill_dense(DV, V, state);

    for(int i = 0; i < n; ++i) {
        //U_dat[m * i + 1] *= scaling_factor_U;
        for(int j = 0; j < 10; ++j) {
            U[m * i + j] *= scaling_factor_U;
        }
    }

    lapack::geqrf(m, n, U, m, tau1);
    lapack::ungqr(m, n, n, U, m, tau1);

    lapack::geqrf(n, n, V, n, tau2);
    lapack::ungqr(n, n, n, V, n, tau2);

    // Grab an upper-triangular portion of V
    RandLAPACK::util::get_U(n, n, V, n);

    for(int i = 11; i < n; ++i)
        V[n * i + i] *= scaling_factor_V;

    blas::gemm(Layout::ColMajor, Op::NoTrans, Op::NoTrans, m, n, n, 1.0, U, m, V, n, 0.0, A, m);

    delete[] U;
    delete[] V;
    delete[] tau1;
    delete[] tau2;
}

/// Per Oleg Balabanov's suggestion, this matrix is supposed to break QB with Cholesky QR.
/// Output matrix is m by n, full-rank.
/// Parameter 'k' signifies the dimension of a sketching operator.
/// Boolean parameter 'diag' signifies whether the matrix is to be
/// generated as diagonal.
/// Parameter 'cond' signfies the condition number of a generated matrix.
template <typename T, typename RNG>
void gen_bad_cholqr_mat(
    int64_t &m,
    int64_t &n,
    T* A,
    int64_t k,
    T cond,
    bool diagon,
    RandBLAS::RNGState<RNG> &state
) {
    T* s = new T[k]();
    T* S = new T[k * k]();

    // The first k singular values will be =1
    int offset = k;
    std::fill(s, s + offset, 1.0);

    // Then, we start with 10^-8 and decrease exponentially
    T t = log(std::pow(10, 8) / cond) / (1 - (n - offset));

    T cnt = 0.0;
    // apply lambda function to every entry of s
    // Please make sure that the first singular value is always 1
    std::for_each(s + offset, s + k,
        // Lambda expression begins
        [&t, &cnt](T &entry) {
                entry = (std::exp(t) / std::pow(10, 8)) * (std::exp(++cnt * -t));
        }
    );

    // form a diagonal S
    RandLAPACK::util::diag(k, k, s, k, S);
    if (diagon) {
        lapack::lacpy(MatrixType::General, k, k, S, k, A, k);
    } else {
        RandLAPACK::gen::gen_singvec(m, n, A, k, S, state);
    }

    delete[] s;
    delete[] S;
}

/// Generates Kahan matrix
template <typename T>
void gen_kahan_mat(
    int64_t m,
    int64_t n,
    T* A,
    T theta,
    T perturb
) {
    T* S = new T[m * m]();
    T* C = new T[m * m]();

    T sin_theta = std::sin(theta);
    T cos_theta = std::cos(theta);

    for (int i = 0; i < n; ++i) {
        A[(m + 1) * i] = perturb * std::numeric_limits<double>::epsilon() * (m - i);
        S[(m + 1) * i] = std::pow(sin_theta, i);
        for(int j = 0; j < i; ++ j)
            C[(m * i) + j] = -cos_theta; 
        C[m * i + i] = 1.0;
    }

    blas::gemm(Layout::ColMajor, Op::NoTrans, Op::NoTrans, m, m, m, 1.0, S, m, C, m, 1.0, A, m);

    delete[] S;
    delete[] C;
}

/// Reads a matrix from a file
template <typename T>
void process_input_mat(
    int64_t &m,
    int64_t &n,
    T* A,
    char* filename,
    int& workspace_query_mod
) {
    // We only check the size of the input data.
    if (workspace_query_mod) {
        std::string line;
        std::string line_entry;

        // Read input file
        std::ifstream inputMat(filename);

        // Count numcols.
        std::getline(inputMat, line);
        std::istringstream lineStream(line);
        while (lineStream >> line_entry)
            ++n;

        // Count numrows - already got through row 1.
        ++m;
        while (std::getline(inputMat, line))
            ++m;

        // Exit querying mod.
        workspace_query_mod = 0;
    } else {
        double value;
        int i, j;
        // Read input file
        std::ifstream inputMat(filename);

        // Place the contents of a file into the matrix space.
        // Matrix is input in a row-major order, we process data in column-major.
        // Reads here are, unfortunately, sequential;
        for(j = 0; j < m; ++j) {
            for(i = 0; i < n; ++i) {
                inputMat >> value;
                A[m * i + j] = value;
            }
        }
    }
}

/// Generate a random dense matrix with specified layout.
/// For simple random matrices without spectral structure.
///
/// @tparam T - Scalar type (double, float, etc.)
/// @tparam RNG - Random number generator type
///
/// @param[in] m - Number of rows
/// @param[in] n - Number of columns
/// @param[out] A - Output matrix (must be pre-allocated with m*n elements)
/// @param[in] layout - Memory layout (ColMajor or RowMajor)
/// @param[in,out] state - RNG state for reproducible generation
/// @param[in] dist - Distribution for matrix entries (Gaussian or Uniform, default: Gaussian)
///
template <typename T, typename RNG>
void gen_random_dense(
    int64_t m,
    int64_t n,
    T* A,
    blas::Layout layout,
    RandBLAS::RNGState<RNG> &state,
    RandBLAS::ScalarDist dist = RandBLAS::ScalarDist::Gaussian
) {
    RandBLAS::DenseDist D(m, n, dist);
    RandBLAS::fill_dense(D, A, state);

    // RandBLAS generates ColMajor; convert to RowMajor if needed
    if (layout == blas::Layout::RowMajor) {
        std::vector<T> temp(A, A + m * n);
        // ColMajor: irs=1, ics=m; RowMajor: irs=n, ics=1
        RandBLAS::util::omatcopy(m, n, temp.data(), 1, m, A, n, 1);
    }
}

/// Generate a random sparse matrix in COO format.
/// Creates a sparse matrix with uniformly random positions and values from the specified distribution.
/// Duplicate (row, col) entries are merged by summing their values.
///
/// @tparam T - Scalar type (double, float, etc.)
/// @tparam RNG - Random number generator type
///
/// @param[in] m - Number of rows
/// @param[in] n - Number of columns
/// @param[in] density - Fraction of entries that are nonzero (0 < density <= 1)
/// @param[in,out] state - RNG state for reproducible generation
/// @param[in] dist - Distribution for nonzero values (Gaussian or Uniform, default: Gaussian)
///
/// @return COO matrix with at most m*n*density nonzero entries (fewer if duplicates were merged)
///
template <typename T, typename RNG>
RandBLAS::sparse_data::coo::COOMatrix<T> gen_sparse_coo(
    int64_t m,
    int64_t n,
    T density,
    RandBLAS::RNGState<RNG> &state,
    RandBLAS::ScalarDist dist = RandBLAS::ScalarDist::Gaussian
) {
    using namespace RandBLAS::sparse_data;

    int64_t target_nnz = static_cast<int64_t>(m * n * density);

    // Generate random values from specified distribution
    std::vector<T> vals_tmp(target_nnz);
    RandBLAS::DenseDist D(target_nnz, 1, dist);
    state = RandBLAS::fill_dense(D, vals_tmp.data(), state);

    // Generate uniformly random row and column indices
    std::vector<int64_t> row_indices(target_nnz);
    std::vector<int64_t> col_indices(target_nnz);
    state = RandBLAS::sample_indices_iid_uniform(m, target_nnz, row_indices.data(), state);
    state = RandBLAS::sample_indices_iid_uniform(n, target_nnz, col_indices.data(), state);

    // Use map to deduplicate: key = (row * n + col), value = accumulated sum
    std::unordered_map<int64_t, T> entries;
    for (int64_t idx = 0; idx < target_nnz; ++idx) {
        int64_t key = row_indices[idx] * n + col_indices[idx];
        entries[key] += vals_tmp[idx];  // Sum duplicates
    }

    // Build deduplicated COO matrix
    int64_t actual_nnz = static_cast<int64_t>(entries.size());
    coo::COOMatrix<T> A_coo(m, n);
    coo::reserve_coo(actual_nnz, A_coo);

    int64_t idx = 0;
    for (const auto& [key, val] : entries) {
        A_coo.rows[idx] = key / n;
        A_coo.cols[idx] = key % n;
        A_coo.vals[idx] = val;
        ++idx;
    }

    return A_coo;
}

/// Generate a random sparse matrix in CSC format.
/// Convenience wrapper around gen_sparse_coo that converts to CSC.
///
/// @tparam T - Scalar type (double, float, etc.)
/// @tparam RNG - Random number generator type
///
/// @param[in] m - Number of rows
/// @param[in] n - Number of columns
/// @param[in] density - Fraction of entries that are nonzero (0 < density <= 1)
/// @param[in,out] state - RNG state for reproducible generation
/// @param[in] dist - Distribution for nonzero values (Gaussian or Uniform, default: Gaussian)
///
/// @return CSC matrix with at most m*n*density nonzero entries
///
template <typename T, typename RNG>
RandBLAS::sparse_data::CSCMatrix<T> gen_sparse_csc(
    int64_t m,
    int64_t n,
    T density,
    RandBLAS::RNGState<RNG> &state,
    RandBLAS::ScalarDist dist = RandBLAS::ScalarDist::Gaussian
) {
    auto coo = gen_sparse_coo<T>(m, n, density, state, dist);
    RandBLAS::sparse_data::CSCMatrix<T> csc(m, n);
    RandBLAS::sparse_data::conversions::coo_to_csc(coo, csc);
    return csc;
}

/// Alias for gen_sparse_coo for backwards compatibility
template <typename T, typename RNG>
RandBLAS::sparse_data::coo::COOMatrix<T> gen_sparse_mat(
    int64_t m,
    int64_t n,
    T density,
    RandBLAS::RNGState<RNG> &state,
    RandBLAS::ScalarDist dist = RandBLAS::ScalarDist::Gaussian
) {
    return gen_sparse_coo<T>(m, n, density, state, dist);
}

/// Generate a tall sparse m×n matrix with a specified condition number.
///
/// Constructs the matrix by stacking copies of the transpose of a banded Cholesky
/// factor. The method:
///   1. Generates an n×n banded SPD seed matrix (pentadiagonal by default)
///   2. Computes its eigenvalue range via LAPACK sbev
///   3. Applies a diagonal shift to achieve κ(G) = cond_num²
///   4. Computes banded Cholesky: G = L L^T via LAPACK pbtrf
///   5. Stacks ceil(m/n) copies of L^T to form the m×n output matrix
///
/// The resulting matrix has κ₂(A) = cond_num exactly (up to minor perturbation
/// when m is not a multiple of n). Sparsity is ~(2*bandwidth+1) nonzeros per row.
///
/// @tparam T       Scalar type (double, float)
/// @tparam RNG     Random number generator type
///
/// @param[in]     m          Number of rows (must satisfy m >= n)
/// @param[in]     n          Number of columns
/// @param[in]     cond_num   Target condition number (must be >= 1)
/// @param[in,out] state      RNG state for reproducible generation
/// @param[in]     bandwidth  Half-bandwidth of the banded seed (default: 2 = pentadiagonal)
///
/// @return COO matrix of dimensions m×n with the specified condition number
///
template <typename T, typename RNG>
RandBLAS::sparse_data::coo::COOMatrix<T> gen_sparse_cond_coo(
    int64_t m,
    int64_t n,
    T cond_num,
    RandBLAS::RNGState<RNG> &state,
    int64_t bandwidth = 2
) {
    using namespace RandBLAS::sparse_data;

    randblas_require(m >= n);
    randblas_require(n >= 1);
    randblas_require(cond_num >= (T)1.0);

    int64_t kd = bandwidth;
    int64_t ldab = kd + 1;

    // ---- Step 1: Build n×n banded SPD seed in LAPACK lower-banded format ----
    // AB layout (Uplo::Lower): AB[(i-j) + j*ldab] = A(i,j) for j <= i <= min(n-1, j+kd)
    // Row 0 of AB = diagonal, row b of AB = b-th subdiagonal.
    std::vector<T> AB(ldab * n, (T)0.0);

    // Diagonal: large enough for diagonal dominance
    for (int64_t j = 0; j < n; ++j) {
        AB[0 + j * ldab] = (T)(2 * (kd + 1));
    }

    // Off-diagonal bands: small random positive values
    RandBLAS::DenseDist dist(1, 1);
    for (int64_t band = 1; band <= kd; ++band) {
        for (int64_t j = 0; j < n - band; ++j) {
            // Entry A(j+band, j) stored at AB[band + j*ldab]
            T val;
            state = RandBLAS::fill_dense(dist, &val, state);
            AB[band + j * ldab] = std::abs(val) * (T)0.5;
        }
    }

    // ---- Step 2: Compute eigenvalue range via sbev ----
    // sbev destroys AB, so work on a copy
    std::vector<T> AB_eig(AB);
    std::vector<T> eigenvalues(n);
    T z_dummy;
    int64_t info = lapack::sbev(
        lapack::Job::NoVec, lapack::Uplo::Lower,
        n, kd, AB_eig.data(), ldab,
        eigenvalues.data(), &z_dummy, 1
    );
    if (info != 0) {
        throw std::runtime_error(
            "gen_sparse_cond_coo: sbev failed with info = " + std::to_string(info));
    }
    T lambda_min = eigenvalues[0];
    T lambda_max = eigenvalues[n - 1];

    // ---- Step 3: Compute diagonal shift for κ(G) = cond_num² ----
    T kappa_sq = cond_num * cond_num;
    T alpha = (T)0.0;
    if (cond_num > (T)1.0) {
        alpha = (lambda_max - kappa_sq * lambda_min) / (kappa_sq - (T)1.0);
    } else {
        // cond_num == 1: shift to make all eigenvalues equal to lambda_max
        alpha = lambda_max - lambda_min;
    }

    // ---- Step 4: Apply shift and compute banded Cholesky ----
    for (int64_t j = 0; j < n; ++j) {
        AB[0 + j * ldab] += alpha;
    }

    info = lapack::pbtrf(lapack::Uplo::Lower, n, kd, AB.data(), ldab);
    if (info != 0) {
        throw std::runtime_error(
            "gen_sparse_cond_coo: pbtrf failed with info = " + std::to_string(info));
    }
    // AB now contains L in lower-banded format:
    //   L(i,j) = AB[(i-j) + j*ldab]  for j <= i <= min(n-1, j+kd)

    // ---- Step 5: Stack copies of L^T into m×n COO ----
    // L^T has entry at (i,j) when 0 <= j-i <= kd, i.e., j in [i, min(n-1, i+kd)]
    // Value: L^T(i,j) = L(j,i) = AB[(j-i) + i*ldab]

    int64_t k_copies = (m + n - 1) / n;  // ceil(m/n)

    // Count nnz per L^T block (same for all full blocks)
    int64_t nnz_per_full_block = 0;
    for (int64_t i = 0; i < n; ++i) {
        for (int64_t j = i; j <= std::min(n - 1, i + kd); ++j) {
            ++nnz_per_full_block;
        }
    }

    // Count total nnz (last block may be truncated)
    int64_t total_nnz = 0;
    for (int64_t blk = 0; blk < k_copies; ++blk) {
        int64_t row_offset = blk * n;
        if (row_offset + n <= m) {
            total_nnz += nnz_per_full_block;
        } else {
            // Truncated last block
            int64_t rows_left = m - row_offset;
            for (int64_t i = 0; i < rows_left; ++i) {
                for (int64_t j = i; j <= std::min(n - 1, i + kd); ++j) {
                    ++total_nnz;
                }
            }
        }
    }

    // Build COO matrix
    coo::COOMatrix<T> A_coo(m, n);
    A_coo.reserve(total_nnz);

    int64_t idx = 0;
    for (int64_t blk = 0; blk < k_copies; ++blk) {
        int64_t row_offset = blk * n;
        int64_t rows_in_block = std::min(n, m - row_offset);
        for (int64_t i = 0; i < rows_in_block; ++i) {
            for (int64_t j = i; j <= std::min(n - 1, i + kd); ++j) {
                A_coo.rows[idx] = row_offset + i;
                A_coo.cols[idx] = j;
                // L^T(i,j) = L(j,i) = AB[(j-i) + i*ldab]
                A_coo.vals[idx] = AB[(j - i) + i * ldab];
                ++idx;
            }
        }
    }

    return A_coo;
}

/// Generate a tall sparse m×n matrix with a specified condition number (CSC format).
/// Convenience wrapper around gen_sparse_cond_coo that converts to CSC.
template <typename T, typename RNG>
RandBLAS::sparse_data::CSCMatrix<T> gen_sparse_cond_csc(
    int64_t m,
    int64_t n,
    T cond_num,
    RandBLAS::RNGState<RNG> &state,
    int64_t bandwidth = 2
) {
    auto coo = gen_sparse_cond_coo<T>(m, n, cond_num, state, bandwidth);
    RandBLAS::sparse_data::CSCMatrix<T> csc(m, n);
    RandBLAS::sparse_data::conversions::coo_to_csc(coo, csc);
    return csc;
}

/// Alias for gen_sparse_cond_coo (matching gen_sparse_mat pattern)
template <typename T, typename RNG>
RandBLAS::sparse_data::coo::COOMatrix<T> gen_sparse_cond_mat(
    int64_t m,
    int64_t n,
    T cond_num,
    RandBLAS::RNGState<RNG> &state,
    int64_t bandwidth = 2
) {
    return gen_sparse_cond_coo<T>(m, n, cond_num, state, bandwidth);
}

/// 'Entry point' routine for matrix generation.
/// Calls functions for different mat type to fill the contents of a provided standard vector.
template <typename T, typename RNG>
void mat_gen(
    mat_gen_info<T> &info,
    T* A,
    RandBLAS::RNGState<RNG> &state
) {

    switch(info.m_type) {
        case polynomial:
                // Generating matrix with polynomially decaying singular values
                RandLAPACK::gen::gen_poly_mat(info.rows, info.cols, A, info.rank, info.frac_spectrum_one, info.cond_num, info.exponent, info.diag, state);
                break;
        case exponential:
                // Generating matrix with exponentially decaying singular values
                RandLAPACK::gen::gen_exp_mat(info.rows, info.cols, A, info.rank, info.cond_num, info.diag, state);
                break;
            break;
        case gaussian: {
                // Gaussian random matrix
                RandBLAS::DenseDist D(info.rows, info.cols);
                state = RandBLAS::fill_dense(D, A, state);
            }
            break;
        case step: {
                // Generating matrix with a staircase-like spectrum
                RandLAPACK::gen::gen_step_mat(info.rows, info.cols, A, info.rank, info.cond_num, info.diag, state);
            }    
            break;
        case spiked: {
                // This matrix may be numerically rank deficient
                RandLAPACK::gen::gen_spiked_mat(info.rows, info.cols, A, info.scaling, state);
                if(info.check_true_rank)
                    info.rank = RandLAPACK::util::rank_check(info.rows, info.cols, A);
            }
            break;
        case adverserial: {
                // This matrix may be numerically rank deficient
                RandLAPACK::gen::gen_oleg_adversarial_mat(info.rows, info.cols, A, info.scaling, state);
                if(info.check_true_rank)
                    info.rank = RandLAPACK::util::rank_check(info.rows, info.cols, A);
            }
            break;
        case bad_cholqr: {
                // Per Oleg's suggestion, this is supposed to make QB fail with CholQR for orth/stab
                RandLAPACK::gen::gen_bad_cholqr_mat(info.rows, info.cols, A, info.rank, info.cond_num, info.diag, state);
            }
            break;
        case kahan: {
                // Generates Kahan Matrix
                RandLAPACK::gen::gen_kahan_mat(info.rows, info.cols, A, info.theta, info.perturb);
            }
            break;
        case custom_input: {
                // Generates Kahan Matrix
                RandLAPACK::gen::process_input_mat(info.rows, info.cols, A, info.filename, info.workspace_query_mod);
            }
            break;
        default:
            throw std::runtime_error(std::string("Unrecognized case."));
            break;
    }
}

template <typename T, typename RNG>
::std::vector<T> mat_gen(mat_gen_info<T> &info, RandBLAS::RNGState<RNG> &state) {
    ::std::vector<T> A(info.rows * info.cols, 0.0);
    mat_gen(info, A.data(), state);
    return A;
}

/// @brief Generate a symmetric positive definite (SPD) matrix with specified condition number.
///
/// Generates an SPD matrix A = Q * D * Q^T where:
/// - D is diagonal with eigenvalues: λ_i = 1 + (cond_num - 1) * ((i-1)/(n-1))^2
///   This gives λ_1 = 1, λ_n = cond_num, so κ(A) = cond_num
/// - Q is a random orthogonal matrix generated via QR factorization of a Gaussian matrix
///
/// This implementation avoids the duplicate-summing bug present in some earlier versions.
///
/// @tparam T Scalar type (double, float, etc.)
/// @tparam RNG Random number generator type
///
/// @param[in] n Dimension of square SPD matrix (n × n)
/// @param[in] cond_num Target condition number for the matrix
/// @param[out] A Output buffer for the n×n SPD matrix (column-major)
/// @param[in,out] state RNG state for reproducible generation
///
template <typename T, typename RNG>
void gen_spd_mat(
    int64_t n,
    T cond_num,
    T* A,
    RandBLAS::RNGState<RNG> &state
) {
    // Step 1: Generate eigenvalues with desired condition number
    // Use polynomial decay: λ_i = 1 + (cond_num - 1) * ((i-1)/(n-1))^2
    std::vector<T> eigenvalues(n);
    eigenvalues[0] = 1.0;  // Smallest eigenvalue
    if (n > 1) {
        eigenvalues[n-1] = cond_num;  // Largest eigenvalue
        for (int64_t i = 1; i < n - 1; ++i) {
            T t = static_cast<T>(i) / static_cast<T>(n - 1);
            eigenvalues[i] = 1.0 + (cond_num - 1.0) * t * t;
        }
    }

    // Step 2: Generate random orthogonal matrix Q via QR factorization
    std::vector<T> Q(n * n);
    std::vector<T> tau(n);

    // Fill Q with Gaussian random entries
    auto d = RandBLAS::DenseDist(n, n);
    RandBLAS::fill_dense(d, Q.data(), state);

    // QR factorization to get orthogonal Q
    lapack::geqrf(n, n, Q.data(), n, tau.data());
    lapack::orgqr(n, n, n, Q.data(), n, tau.data());

    // Step 3: Form A = Q * D * Q^T
    // First compute Q_scaled = Q * D (scale columns of Q by eigenvalues)
    std::vector<T> Q_scaled(n * n);
    for (int64_t j = 0; j < n; ++j) {
        for (int64_t i = 0; i < n; ++i) {
            Q_scaled[i + j * n] = Q[i + j * n] * eigenvalues[j];
        }
    }

    // Then A = Q_scaled * Q^T
    blas::gemm(Layout::ColMajor, Op::NoTrans, Op::Trans,
               n, n, n, (T)1.0, Q_scaled.data(), n, Q.data(), n, (T)0.0, A, n);
}

}
