// rl_config.hh is generated by CMake and installed, but nothing in the library
// includes it, so for a long time nothing compiled it and it silently stopped being
// valid C++. These tests are cheap; their real job is to keep that from recurring.

#include "RandLAPACK/rl_config.hh"

#include <gtest/gtest.h>
#include <string>

class TestConfig : public ::testing::Test {};

TEST_F(TestConfig, version_macros_are_defined) {
    // Compilation is the substantive check. These assertions document what the header
    // is expected to provide.
    std::string version = RandLAPACK_VERSION;
    EXPECT_FALSE(version.empty());

    EXPECT_GE(RandLAPACK_VERSION_MAJOR, 0);
    EXPECT_GE(RandLAPACK_VERSION_MINOR, 0);
    EXPECT_GE(RandLAPACK_VERSION_PATCH, 0);
}

TEST_F(TestConfig, version_string_starts_with_the_numeric_components) {
    // rl_version.cmake derives the components from `git describe`, so the string always
    // begins with MAJOR.MINOR.PATCH and may carry a commit suffix after that.
    std::string expected_prefix =
        std::to_string(RandLAPACK_VERSION_MAJOR) + "." +
        std::to_string(RandLAPACK_VERSION_MINOR) + "." +
        std::to_string(RandLAPACK_VERSION_PATCH);
    std::string version = RandLAPACK_VERSION;

    EXPECT_EQ(version.rfind(expected_prefix, 0), 0u)
        << "version string \"" << version << "\" does not start with \""
        << expected_prefix << "\"";
}
