#pragma once

#include "rl_blaspp.hh"
#include "rl_lapackpp.hh"

#include <RandBLAS.hh>
#include <iostream>
#include <cmath>
#include <algorithm>
#include <vector>
#include <cstdint>
#include <sstream>
#include <fstream>
#include <unordered_map>

namespace RandLAPACK::gen {

/// An enumeration describing various matrix types by name.
/// Each matrix type can be generated bt mat_gen() utility function.
/// This list is expected to grow.
enum mat_type {
    polynomial, 
    exponential, 
    gaussian, 
    step, 
    spiked, 
    adverserial, 
    bad_cholqr,
    kahan,
    custom_input};

/// A struct containing info about a given matrix to be generated by mat_gen().
/// Requires only the size and type of a matrix by default, but can have other optional parameters.
template <typename T>
struct mat_gen_info {
    int64_t rows;
    int64_t cols;
    int64_t rank = std::min(rows, cols);
    mat_type m_type;
    T cond_num = 1.0;
    T scaling = 1.0;
    T exponent = 1.0;
    bool diag = false;
    bool check_true_rank = false;
    T theta = 1.0;
    T perturb = 1.0;
    char* filename;
    int workspace_query_mod;
    T frac_spectrum_one = 0.1;

    mat_gen_info(int64_t& m, int64_t& n, mat_type t) {
        rows = m;
        cols = n;
        m_type = t;
        rank = n; // < default
    }
};

/// Given singular values, generates left and right singular vectors and combines all into a single matrix.
/// Note: Printed matrix A may have different rank from actual generated matrix A
template <typename T, typename RNG>
void gen_singvec(
    int64_t m,
    int64_t n,
    T* A,
    int64_t k,
    T* S,
    RandBLAS::RNGState<RNG> &state
) {
    std::fill(&A[0], &A[m * n], 0.0);
    T* U   = new T[m * k]();
    T* V   = new T[n * k]();
    T* tau = new T[k]();

    RandBLAS::DenseDist DU(m, k);
    RandBLAS::DenseDist DV(n, k);
    state = RandBLAS::fill_dense(DU, U, state);
    state = RandBLAS::fill_dense(DV, V, state);

    blas::copy(k, S, k + 1, A, m + 1);

    lapack::geqrf(m, k, U, m, tau);
    lapack::ormqr(Side::Left, Op::NoTrans, m, n, k, U, m, tau, A, m);

    lapack::geqrf(n, k, V, n, tau);
    lapack::ormqr(Side::Right, Op::Trans, m, n, k, V, n, tau, A, m);

    delete[] U;
    delete[] V;
    delete[] tau;
}

/// Generate a vector of k polynomially-decaying singular values of the form:
/// s_i = a(i + b)^p, where p is the user-defined exponent constant, a and b are computed
/// using p and the user-defined condition number parameter. The first
/// frac_spectrum_one fraction of the singular values are set to one.
///
/// @param[in] k                  Number of singular values
/// @param[in] frac_spectrum_one  Fraction of singular values set to 1.0
/// @param[in] cond               Condition number (ratio of largest to smallest singular value)
/// @param[in] p                  Polynomial decay exponent
///
/// @return Vector of k singular values
template <typename T>
std::vector<T> gen_poly_singvals(
    int64_t k,
    T frac_spectrum_one,
    T cond,
    T p
) {
    std::vector<T> s(k);
    int offset = (int) floor(k * frac_spectrum_one);
    T first_entry = 1.0;
    T last_entry = first_entry / cond;
    T neg_invp = -((T)1.0)/p;
    T a = std::pow((std::pow(last_entry, neg_invp) - std::pow(first_entry, neg_invp)) / (k - offset), p);
    T b = std::pow(a * first_entry, neg_invp) - offset;
    std::fill(s.begin(), s.begin() + offset, 1.0);
    int idx = offset;
    for (int i = offset; i < k; ++i) {
        s[i] = 1 / (a * std::pow(idx + b, p));
        ++idx;
    }
    return s;
}

/// Generates a matrix with polynomially-decaying spectrum of the following form:
/// s_i = a(i + b)^p, where p is the user-defined exponent constant, a and b are computed
/// using p and the user-defined condition number parameter and the first 10 percent of the
/// singular values are equal to one.
/// User can optionally choose for the matrix to be diagonal.
/// The output matrix has k singular values.
template <typename T, typename RNG>
void gen_poly_mat(
    int64_t &m,
    int64_t &n,
    T* A,
    int64_t k,
    T frac_spectrum_one,
    T cond,
    T p,
    bool diagon,
    RandBLAS::RNGState<RNG> &state
) {
    auto s = gen_poly_singvals(k, frac_spectrum_one, cond, p);

    T* S = new T[k * k]();
    RandLAPACK::util::diag(k, k, s.data(), k, S);

    if (diagon) {
        lapack::lacpy(MatrixType::General, k, k, S, k, A, k);
    } else {
        RandLAPACK::gen::gen_singvec(m, n, A, k, S, state);
    }

    delete[] S;
}

/// Generate k exponentially-decaying singular values:
///   s_i = e^((i + 1) * -t), where t = log(cond) / (k - offset).
/// The first 10% of the singular values are set to one.
///
/// @param[in] k     Number of singular values
/// @param[in] cond  Condition number
///
/// @return Vector of k singular values
template <typename T>
std::vector<T> gen_exp_singvals(int64_t k, T cond) {
    std::vector<T> s(k);
    int offset = (int) floor(k * 0.1);
    T t = -log(1 / cond) / (k - offset);
    T cnt = 0.0;
    std::fill(s.begin(), s.begin() + offset, 1.0);
    int idx = offset;
    for (int i = offset; i < k; ++i) {
        s[i] = std::exp(++cnt * -t);
        ++idx;
    }
    return s;
}

/// Generates a matrix with exponentially-decaying spectrum.
/// User can optionally choose for the matrix to be diagonal.
/// The output matrix has k singular values.
template <typename T, typename RNG>
void gen_exp_mat(
    int64_t &m,
    int64_t &n,
    T* A,
    int64_t k,
    T cond,
    bool diagon,
    RandBLAS::RNGState<RNG> &state
) {
    auto s = gen_exp_singvals(k, cond);

    T* S = new T[k * k]();
    RandLAPACK::util::diag(k, k, s.data(), k, S);

    if (diagon) {
        lapack::lacpy(MatrixType::General, k, k, S, k, A, k);
    } else {
        RandLAPACK::gen::gen_singvec(m, n, A, k, S, state);
    }

    delete[] S;
}

/// Generate k staircase singular values with 4 steps controlled by
/// the condition number, starting at 1.
///
/// @param[in] k     Number of singular values
/// @param[in] cond  Condition number
///
/// @return Vector of k singular values
template <typename T>
std::vector<T> gen_step_singvals(int64_t k, T cond) {
    std::vector<T> s(k);
    int offset = (int) (k / 4);
    std::fill(s.begin(), s.begin() + offset, 1.0);
    std::fill(s.begin() + offset, s.begin() + 2 * offset, 8.0 / cond);
    std::fill(s.begin() + 2 * offset, s.begin() + 3 * offset, 4.0 / cond);
    std::fill(s.begin() + 3 * offset, s.end(), 1.0 / cond);
    return s;
}

/// Generates matrix with a staircase spectrum with 4 steps.
/// Output matrix is m by n of rank k.
/// User can optionally choose for the matrix to be diagonal.
template <typename T, typename RNG>
void gen_step_mat(
    int64_t &m,
    int64_t &n,
    T* A,
    int64_t k,
    T cond,
    bool diagon,
    RandBLAS::RNGState<RNG> &state
) {
    auto s = gen_step_singvals(k, cond);

    T* S = new T[k * k]();
    RandLAPACK::util::diag(k, k, s.data(), k, S);

    if (diagon) {
        lapack::lacpy(MatrixType::General, k, k, S, k, A, k);
    } else {
        RandLAPACK::gen::gen_singvec(m, n, A, k, S, state);
    }

    delete[] S;
}

/// Generates a matrix with high coherence between the left singular vectors.
/// Output matrix is m by n, full-rank.
/// Such matrix would be difficult to sketch.
/// Right singular vectors are sampled uniformly at random.
template <typename T, typename RNG>
void gen_spiked_mat(
    int64_t &m,
    int64_t &n,
    T* A,
    T spike_scale,
    RandBLAS::RNGState<RNG> &state
) {

    int64_t num_rows_sampled = n / 2;

    /// sample from [m] without replacement. Get the row indices for a tall LASO with a single column.
    int64_t* rows   = new int64_t[num_rows_sampled]();
    state = RandBLAS::repeated_fisher_yates(num_rows_sampled, m, 1, rows, state);

    T* V   = new T[n * n]();
    T* tau = new T[n]();

    RandBLAS::DenseDist DV(n, n);
    state = RandBLAS::fill_dense(DV, V, state);

    lapack::geqrf(n, n, V, n, tau);
    lapack::ungqr(n, n, n, V, n, tau);

    // Fill A with stacked copies of V
    int64_t size = 0;
    int i, j;

    while(size < m){
        lapack::lacpy(MatrixType::General, std::min(n, m - size), n, V, n, &A[size], m);
        size += std::min(n, m - size);
    }

    for (i = 0; i < n; ++ i) {
        for (j = 0; j < num_rows_sampled; ++j) {
            A[m * i + rows[j]] *= spike_scale;
        }
        j = 0;
    }

    delete[] rows;
    delete[] V;
    delete[] tau;
}

/// Generates a numerically rank-deficient matrix.
/// Added per Oleg's suggestion.
/// Output matrix is m by n of some rank k < n.
/// Generates a matrix of the form A = UV, where
/// U is an m by n Gaussian matrix whose first row was scaled by a factor sigma, and that then 
/// was orthonormalized with a Householder QR. 
/// The matrix V is the upper triangular part of an n × n 
/// orthonormalized Gaussian matrix with modified diagonal entries to diag(V) *= [1, 10^-15, . . . , 10^-15, 10^-15].
template <typename T, typename RNG>
void gen_oleg_adversarial_mat(
    int64_t &m,
    int64_t &n,
    T* A,
    T sigma,
    RandBLAS::RNGState<RNG> &state
) {

    T scaling_factor_U = sigma;
    T scaling_factor_V = 10e-3;

    T* U    = new T[m * n]();
    T* V    = new T[n * n]();
    T* tau1 = new T[n]();
    T* tau2 = new T[n]();

    RandBLAS::DenseDist DU(m, n);
    state = RandBLAS::fill_dense(DU, U, state);

    RandBLAS::DenseDist DV(n, n);
    state = RandBLAS::fill_dense(DV, V, state);

    for(int i = 0; i < n; ++i) {
        //U_dat[m * i + 1] *= scaling_factor_U;
        for(int j = 0; j < 10; ++j) {
            U[m * i + j] *= scaling_factor_U;
        }
    }

    lapack::geqrf(m, n, U, m, tau1);
    lapack::ungqr(m, n, n, U, m, tau1);

    lapack::geqrf(n, n, V, n, tau2);
    lapack::ungqr(n, n, n, V, n, tau2);

    // Grab an upper-triangular portion of V
    RandLAPACK::util::get_U(n, n, V, n);

    for(int i = 11; i < n; ++i)
        V[n * i + i] *= scaling_factor_V;

    blas::gemm(Layout::ColMajor, Op::NoTrans, Op::NoTrans, m, n, n, 1.0, U, m, V, n, 0.0, A, m);

    delete[] U;
    delete[] V;
    delete[] tau1;
    delete[] tau2;
}

/// Generate singular values for the "bad CholQR" matrix.
/// The first k values are 1, then values start at 10^-8 and decrease
/// exponentially, controlled by cond and n.
///
/// @param[in] k     Number of singular values (= sketching dimension)
/// @param[in] n     Number of columns in the target matrix
/// @param[in] cond  Condition number
///
/// @return Vector of k singular values
template <typename T>
std::vector<T> gen_bad_cholqr_singvals(int64_t k, int64_t n, T cond) {
    std::vector<T> s(k, 1.0);
    int offset = k;
    T t = log(std::pow(10, 8) / cond) / (1 - (n - offset));
    T cnt = 0.0;
    for (int i = offset; i < k; ++i) {
        s[i] = (std::exp(t) / std::pow(10, 8)) * (std::exp(++cnt * -t));
    }
    return s;
}

/// Per Oleg Balabanov's suggestion, this matrix is supposed to break QB with Cholesky QR.
/// Output matrix is m by n, full-rank.
template <typename T, typename RNG>
void gen_bad_cholqr_mat(
    int64_t &m,
    int64_t &n,
    T* A,
    int64_t k,
    T cond,
    bool diagon,
    RandBLAS::RNGState<RNG> &state
) {
    auto s = gen_bad_cholqr_singvals(k, n, cond);

    T* S = new T[k * k]();
    RandLAPACK::util::diag(k, k, s.data(), k, S);

    if (diagon) {
        lapack::lacpy(MatrixType::General, k, k, S, k, A, k);
    } else {
        RandLAPACK::gen::gen_singvec(m, n, A, k, S, state);
    }

    delete[] S;
}

/// Generates Kahan matrix
template <typename T>
void gen_kahan_mat(
    int64_t m,
    int64_t n,
    T* A,
    T theta,
    T perturb
) {
    T* S = new T[m * m]();
    T* C = new T[m * m]();

    T sin_theta = std::sin(theta);
    T cos_theta = std::cos(theta);

    for (int i = 0; i < n; ++i) {
        A[(m + 1) * i] = perturb * std::numeric_limits<double>::epsilon() * (m - i);
        S[(m + 1) * i] = std::pow(sin_theta, i);
        for(int j = 0; j < i; ++ j)
            C[(m * i) + j] = -cos_theta; 
        C[m * i + i] = 1.0;
    }

    blas::gemm(Layout::ColMajor, Op::NoTrans, Op::NoTrans, m, m, m, 1.0, S, m, C, m, 1.0, A, m);

    delete[] S;
    delete[] C;
}

/// Reads a matrix from a file
template <typename T>
void process_input_mat(
    int64_t &m,
    int64_t &n,
    T* A,
    char* filename,
    int& workspace_query_mod
) {
    // We only check the size of the input data.
    if (workspace_query_mod) {
        std::string line;
        std::string line_entry;

        // Read input file
        std::ifstream inputMat(filename);

        // Count numcols.
        std::getline(inputMat, line);
        std::istringstream lineStream(line);
        while (lineStream >> line_entry)
            ++n;

        // Count numrows - already got through row 1.
        ++m;
        while (std::getline(inputMat, line))
            ++m;

        // Exit querying mod.
        workspace_query_mod = 0;
    } else {
        // Fast matrix read: slurp file into memory, locate row boundaries,
        // then parse rows in parallel with strtod + OpenMP.
        //
        // Why not use ifstream >> ?
        //   C++ formatted stream extraction (operator>>) is extremely slow for
        //   large matrices — parsing 100M doubles takes ~30s. This approach:
        //     1. fread the entire file into a char buffer  (~2s for 800MB, I/O-bound)
        //     2. Scan for newlines to find row boundaries   (~0.1s, memory-bandwidth)
        //     3. Parse each row independently via strtod    (~1s with OpenMP)
        //   Total: ~3s vs ~30s — roughly 10x faster.
        //
        // Note: input file is row-major text (whitespace-separated doubles,
        // one row per line). We store in column-major: A[m * col + row].

        // Step 1: Read entire file into memory.
        FILE* fp = std::fopen(filename, "r");
        if (!fp)
            throw std::runtime_error(std::string("Cannot open file: ") + filename);
        std::fseek(fp, 0, SEEK_END);
        long file_size = std::ftell(fp);
        std::fseek(fp, 0, SEEK_SET);

        std::vector<char> buf(file_size + 1);
        size_t bytes_read = std::fread(buf.data(), 1, file_size, fp);
        (void) bytes_read;
        buf[file_size] = '\0';
        std::fclose(fp);

        // Step 2: Find the starting byte offset of each row.
        std::vector<char*> row_starts(m);
        row_starts[0] = buf.data();
        int64_t row_idx = 1;
        for (long pos = 0; pos < file_size && row_idx < m; ++pos) {
            if (buf[pos] == '\n') {
                row_starts[row_idx++] = buf.data() + pos + 1;
            }
        }

        // Step 3: Parse each row in parallel.
        // strtod is thread-safe (no shared state). Each thread handles a
        // contiguous block of rows and writes to non-overlapping columns of A.
        #pragma omp parallel for schedule(static)
        for (int64_t j = 0; j < m; ++j) {
            char* ptr = row_starts[j];
            char* end;
            for (int64_t i = 0; i < n; ++i) {
                A[m * i + j] = (T) std::strtod(ptr, &end);
                ptr = end;
            }
        }
    }
}

/// Generate a random dense matrix with specified layout.
/// For simple random matrices without spectral structure.
///
/// @tparam T - Scalar type (double, float, etc.)
/// @tparam RNG - Random number generator type
///
/// @param[in] m - Number of rows
/// @param[in] n - Number of columns
/// @param[out] A - Output matrix (must be pre-allocated with m*n elements)
/// @param[in] layout - Memory layout (ColMajor or RowMajor)
/// @param[in,out] state - RNG state for reproducible generation
/// @param[in] dist - Distribution for matrix entries (Gaussian or Uniform, default: Gaussian)
///
template <typename T, typename RNG>
void gen_random_dense(
    int64_t m,
    int64_t n,
    T* A,
    blas::Layout layout,
    RandBLAS::RNGState<RNG> &state,
    RandBLAS::ScalarDist dist = RandBLAS::ScalarDist::Gaussian
) {
    RandBLAS::DenseDist D(m, n, dist);
    state = RandBLAS::fill_dense(D, A, state);

    // RandBLAS generates ColMajor; convert to RowMajor if needed
    if (layout == blas::Layout::RowMajor) {
        std::vector<T> temp(A, A + m * n);
        // ColMajor: irs=1, ics=m; RowMajor: irs=n, ics=1
        RandBLAS::util::omatcopy(m, n, temp.data(), 1, m, A, n, 1);
    }
}

/// Generate a random sparse matrix in COO format.
/// Creates a sparse matrix with uniformly random positions and values from the specified distribution.
/// Duplicate (row, col) entries are merged by summing their values.
///
/// @note Future migration: RandBLAS >= commit 7c03be6 provides
/// RandBLAS::testing::random_coo/csr/csc in RandBLAS/testing/sparse_data.hh,
/// which use geometric skips (no duplicate handling, slightly lower constant factor).
/// Once RandBLAS is updated, gen_sparse_coo/csc should be replaced by those.
///
/// @tparam T - Scalar type (double, float, etc.)
/// @tparam RNG - Random number generator type
///
/// @param[in] m - Number of rows
/// @param[in] n - Number of columns
/// @param[in] density - Fraction of entries that are nonzero (0 < density <= 1)
/// @param[in,out] state - RNG state for reproducible generation
/// @param[in] dist - Distribution for nonzero values (Gaussian or Uniform, default: Gaussian)
///
/// @return COO matrix with at most m*n*density nonzero entries (fewer if duplicates were merged)
///
template <typename T, typename RNG>
RandBLAS::sparse_data::coo::COOMatrix<T> gen_sparse_coo(
    int64_t m,
    int64_t n,
    T density,
    RandBLAS::RNGState<RNG> &state,
    RandBLAS::ScalarDist dist = RandBLAS::ScalarDist::Gaussian
) {
    using namespace RandBLAS::sparse_data;

    int64_t target_nnz = static_cast<int64_t>(m * n * density);

    // Generate random values from specified distribution
    std::vector<T> vals_tmp(target_nnz);
    RandBLAS::DenseDist D(target_nnz, 1, dist);
    state = RandBLAS::fill_dense(D, vals_tmp.data(), state);

    // Generate uniformly random row and column indices
    std::vector<int64_t> row_indices(target_nnz);
    std::vector<int64_t> col_indices(target_nnz);
    state = RandBLAS::sample_indices_iid_uniform(m, target_nnz, row_indices.data(), state);
    state = RandBLAS::sample_indices_iid_uniform(n, target_nnz, col_indices.data(), state);

    // Use map to deduplicate: key = (row * n + col), value = accumulated sum
    std::unordered_map<int64_t, T> entries;
    for (int64_t idx = 0; idx < target_nnz; ++idx) {
        int64_t key = row_indices[idx] * n + col_indices[idx];
        entries[key] += vals_tmp[idx];  // Sum duplicates
    }

    // Build deduplicated COO matrix
    int64_t actual_nnz = static_cast<int64_t>(entries.size());
    coo::COOMatrix<T> A_coo(m, n);
    coo::reserve_coo(actual_nnz, A_coo);

    int64_t idx = 0;
    for (const auto& [key, val] : entries) {
        A_coo.rows[idx] = key / n;
        A_coo.cols[idx] = key % n;
        A_coo.vals[idx] = val;
        ++idx;
    }

    return A_coo;
}



/// Generate a tall sparse m×n matrix with prescribed singular values.
///
/// Constructs A with the given singular values by:
///   1. Generate Haar-random orthogonal V via QR of Gaussian (geqrf + orgqr)
///   2. Top n rows = diag(σ) · V^T — gives A^T A = V · diag(σ²) · V^T,
///      a generic SPD matrix with fully random eigenvectors
///   3. Apply m-n left Givens rotations to spread rows from top n to all
///      remaining rows — preserves A^T A exactly since (GA)^T(GA) = A^T A
///   4. Convert dense intermediate to COO, dropping exact zeros
///
/// The Haar-random V guarantees A^T A is fully generic (not diagonally
/// dominant, not tridiagonal, not near-diagonal).
///
/// Left Givens rotations are orthogonal, so singular values are preserved
/// exactly: κ(A) = σ_1/σ_n.
///
/// @tparam T       Scalar type (double, float)
/// @tparam RNG     Random number generator type
///
/// @param[in]     m               Number of rows (must satisfy m >= n)
/// @param[in]     n               Number of columns
/// @param[in]     sigma           Array of n singular values (caller-specified)
/// @param[in,out] state           RNG state for reproducible generation
/// @param[in]     target_density  Target fraction of nonzeros (0,1].
///                                Set to 0 to skip Givens rotations (top n rows only).
///
/// @return COO matrix of dimensions m×n with the specified singular values
///
template <typename T, typename RNG>
RandBLAS::sparse_data::coo::COOMatrix<T> gen_sparse_from_singvals(
    int64_t m,
    int64_t n,
    const T* sigma,
    RandBLAS::RNGState<RNG> &state,
    T target_density = (T)0.0
) {
    using namespace RandBLAS::sparse_data;

    randblas_require(m >= n);
    randblas_require(n >= 1);

    // Build top n×n block as B = diag(σ) · V^T.
    // V is a Haar-random orthogonal matrix from QR of a Gaussian.
    // This gives A^T A = V · diag(σ²) · V^T — a generic SPD matrix with
    // fully random eigenvectors.
    std::vector<T> V(n * n);
    std::vector<T> tau(n);
    auto d_gauss = RandBLAS::DenseDist(n, n);
    state = RandBLAS::fill_dense(d_gauss, V.data(), state);
    lapack::geqrf(n, n, V.data(), n, tau.data());
    lapack::orgqr(n, n, n, V.data(), n, tau.data());

    // A is m×n column-major. Top n rows = diag(σ) · V^T, bottom rows = 0.
    // B(i,j) = σ_i · V^T(i,j) = σ_i · V(j,i)
    std::vector<T> A(m * n, (T)0.0);
    for (int64_t j = 0; j < n; ++j) {
        for (int64_t i = 0; i < n; ++i) {
            A[i + j * m] = sigma[i] * V[j + i * n];
        }
    }

    // Left Givens rotations: populate remaining rows (m - n) for row coverage.
    // Each rotation mixes a populated row with a zero row, spreading entries
    // without changing A^T A (left orthogonal transforms preserve it).
    int64_t n_left  = (target_density > (T)0.0) ? (m - n) : (int64_t)0;

    std::vector<int64_t> source_rows(n_left);   // indices in [0, n)
    std::vector<int64_t> target_rows(n_left);   // indices in [0, m-n)
    std::vector<T> angles(n_left);
    if (n_left > 0) {
        state = RandBLAS::sample_indices_iid_uniform(n, n_left, source_rows.data(), state);
        state = RandBLAS::sample_indices_iid_uniform(m - n, n_left, target_rows.data(), state);
        auto rd = RandBLAS::DenseDist(n_left, 1);
        state = RandBLAS::fill_dense(rd, angles.data(), state);
    }

    for (int64_t rot = 0; rot < n_left; ++rot) {
        int64_t ri = source_rows[rot];
        int64_t rj = n + target_rows[rot];

        T c = std::cos(angles[rot]);
        T s = std::sin(angles[rot]);

        for (int64_t col = 0; col < n; ++col) {
            T ai = A[ri + col * m];
            T aj = A[rj + col * m];
            A[ri + col * m] =  c * ai + s * aj;
            A[rj + col * m] = -s * ai + c * aj;
        }
    }

    // Convert dense to COO, dropping exact zeros.
    coo::COOMatrix<T> A_coo(m, n);
    coo::dense_to_coo(::blas::Layout::ColMajor, A.data(), (T)0.0, A_coo);

    return A_coo;
}

/// Convenience wrapper: generate a tall sparse m×n matrix with log-spaced
/// singular values from 1 to 1/cond_num.
template <typename T, typename RNG>
RandBLAS::sparse_data::coo::COOMatrix<T> gen_sparse_cond_coo(
    int64_t m,
    int64_t n,
    T cond_num,
    RandBLAS::RNGState<RNG> &state,
    T target_density = (T)0.0
) {
    randblas_require(cond_num >= (T)1.0);

    std::vector<T> sigma(n);
    if (n == 1) {
        sigma[0] = (T)1.0;
    } else {
        T log_cond = std::log(cond_num);
        for (int64_t i = 0; i < n; ++i) {
            sigma[i] = std::exp(-((T)i / (T)(n - 1)) * log_cond);
        }
    }

    return gen_sparse_from_singvals(m, n, sigma.data(), state, target_density);
}



/// 'Entry point' routine for matrix generation.
/// Calls functions for different mat type to fill the contents of a provided standard vector.
template <typename T, typename RNG>
void mat_gen(
    mat_gen_info<T> &info,
    T* A,
    RandBLAS::RNGState<RNG> &state
) {

    switch(info.m_type) {
        case polynomial:
                // Generating matrix with polynomially decaying singular values
                RandLAPACK::gen::gen_poly_mat(info.rows, info.cols, A, info.rank, info.frac_spectrum_one, info.cond_num, info.exponent, info.diag, state);
                break;
        case exponential:
                // Generating matrix with exponentially decaying singular values
                RandLAPACK::gen::gen_exp_mat(info.rows, info.cols, A, info.rank, info.cond_num, info.diag, state);
                break;
            break;
        case gaussian: {
                // Gaussian random matrix
                RandBLAS::DenseDist D(info.rows, info.cols);
                state = RandBLAS::fill_dense(D, A, state);
            }
            break;
        case step: {
                // Generating matrix with a staircase-like spectrum
                RandLAPACK::gen::gen_step_mat(info.rows, info.cols, A, info.rank, info.cond_num, info.diag, state);
            }    
            break;
        case spiked: {
                // This matrix may be numerically rank deficient
                RandLAPACK::gen::gen_spiked_mat(info.rows, info.cols, A, info.scaling, state);
                if(info.check_true_rank)
                    info.rank = RandLAPACK::util::rank_check(info.rows, info.cols, A);
            }
            break;
        case adverserial: {
                // This matrix may be numerically rank deficient
                RandLAPACK::gen::gen_oleg_adversarial_mat(info.rows, info.cols, A, info.scaling, state);
                if(info.check_true_rank)
                    info.rank = RandLAPACK::util::rank_check(info.rows, info.cols, A);
            }
            break;
        case bad_cholqr: {
                // Per Oleg's suggestion, this is supposed to make QB fail with CholQR for orth/stab
                RandLAPACK::gen::gen_bad_cholqr_mat(info.rows, info.cols, A, info.rank, info.cond_num, info.diag, state);
            }
            break;
        case kahan: {
                // Generates Kahan Matrix
                RandLAPACK::gen::gen_kahan_mat(info.rows, info.cols, A, info.theta, info.perturb);
            }
            break;
        case custom_input: {
                // Generates Kahan Matrix
                RandLAPACK::gen::process_input_mat(info.rows, info.cols, A, info.filename, info.workspace_query_mod);
            }
            break;
        default:
            throw std::runtime_error(std::string("Unrecognized case."));
            break;
    }
}

template <typename T, typename RNG>
::std::vector<T> mat_gen(mat_gen_info<T> &info, RandBLAS::RNGState<RNG> &state) {
    ::std::vector<T> A(info.rows * info.cols, 0.0);
    mat_gen(info, A.data(), state);
    return A;
}

/// Generate n singular values with quadratic spacing from 1 to cond_num:
///   sigma_i = 1 + (cond_num - 1) * (i/(n-1))^2.
///
/// @param[in] n         Number of singular values
/// @param[in] cond_num  Condition number (ratio of largest to smallest)
///
/// @return Vector of n singular values
template <typename T>
std::vector<T> gen_quadratic_singvals(int64_t n, T cond_num) {
    std::vector<T> s(n);
    s[0] = 1.0;
    if (n > 1) {
        s[n-1] = cond_num;
        for (int64_t i = 1; i < n - 1; ++i) {
            T t = static_cast<T>(i) / static_cast<T>(n - 1);
            s[i] = 1.0 + (cond_num - 1.0) * t * t;
        }
    }
    return s;
}

/// Generate an SPD matrix A = Q * diag(eigvals) * Q^T with prescribed eigenvalues.
///
/// Q is a Haar-random orthogonal matrix (QR of Gaussian). The eigenvalues
/// are used exactly as provided — the caller controls the spectral decay.
///
/// @param[in]     n        Dimension of square SPD matrix (n × n)
/// @param[in]     eigvals  Array of n positive eigenvalues
/// @param[out]    A        Output buffer for the n×n SPD matrix (column-major)
/// @param[in,out] state    RNG state for reproducible generation
///
template <typename T, typename RNG>
void gen_spd_from_eigvals(
    int64_t n,
    const T* eigvals,
    T* A,
    RandBLAS::RNGState<RNG> &state
) {
    // Generate random orthogonal matrix Q via QR factorization of Gaussian
    std::vector<T> Q(n * n);
    std::vector<T> tau(n);

    auto d = RandBLAS::DenseDist(n, n);
    state = RandBLAS::fill_dense(d, Q.data(), state);

    lapack::geqrf(n, n, Q.data(), n, tau.data());
    lapack::orgqr(n, n, n, Q.data(), n, tau.data());

    // Form A = Q * D * Q^T: first Q_scaled = Q * D (scale columns by eigenvalues)
    std::vector<T> Q_scaled(n * n);
    for (int64_t j = 0; j < n; ++j) {
        for (int64_t i = 0; i < n; ++i) {
            Q_scaled[i + j * n] = Q[i + j * n] * eigvals[j];
        }
    }

    // A = Q_scaled * Q^T
    blas::gemm(Layout::ColMajor, Op::NoTrans, Op::Trans,
               n, n, n, (T)1.0, Q_scaled.data(), n, Q.data(), n, (T)0.0, A, n);
}

/// Convenience wrapper: generate an SPD matrix with quadratic eigenvalue decay
/// from 1 to cond_num (λ_i = 1 + (cond_num - 1) * ((i-1)/(n-1))^2).
template <typename T, typename RNG>
void gen_spd_mat(
    int64_t n,
    T cond_num,
    T* A,
    RandBLAS::RNGState<RNG> &state
) {
    auto eigenvalues = gen_quadratic_singvals(n, cond_num);
    gen_spd_from_eigvals(n, eigenvalues.data(), A, state);
}

/// Generate a PSD matrix with polynomial spectral decay via A^T A.
///
/// Uses gen_poly_singvals to generate singular values, gen_singvec to build a
/// full matrix A with those singular values, then forms G = A^T A so that G
/// is PSD with squared spectrum.
///
/// @param[in] m         Matrix dimension (m x m)
/// @param[in] cond_num  Condition number of the intermediate matrix (squared in G)
/// @param[in] exponent  Polynomial decay exponent (squared in G)
/// @param[in] seed      RNG seed
///
/// @return Dense column-major m x m PSD matrix
template <typename T>
std::vector<T> gen_poly_mat_psd(int64_t m, T cond_num, T exponent, uint32_t seed) {
    auto s = gen_poly_singvals(m, (T)0.05, std::sqrt(cond_num), std::sqrt(exponent));

    T* S = new T[m * m]();
    RandLAPACK::util::diag(m, m, s.data(), m, S);

    std::vector<T> A(m * m, 0.0);
    RandBLAS::RNGState<> state(seed);
    gen_singvec(m, m, A.data(), m, S, state);
    delete[] S;

    std::vector<T> G(m * m, 0.0);
    blas::syrk(blas::Layout::ColMajor, blas::Uplo::Upper, blas::Op::NoTrans, m, m, (T)1.0,
        A.data(), m, (T)0.0, G.data(), m);
    RandBLAS::symmetrize(blas::Layout::ColMajor, blas::Uplo::Upper, m, G.data(), m);
    return G;
}

}
