name: benchmark-openmp-macos
on:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2

      - name: webfactory/ssh-agent
        uses: webfactory/ssh-agent@v0.5.4
        with:
            ssh-private-key: ${{ secrets.PRIVATE_CLONE_SSH_KEY }}

      - name: submodule update
        run: |
          git submodule update --init --recursive

      - name: configure OS
        run: |
          # os level stuff
          pwd
          ls
          set -x
          brew install googletest
          # install OpenMP
          export tmp_dir=`pwd`
          cd /usr/local/Cellar/libomp/
          #   there should only be one subdirectory
          cd */
          export libomp_dir=`pwd`
          echo ${libomp_dir}
          ls
          export CXXFLAGS=-I${libomp_dir}/include
          echo $CXXFLAGS
          export LDFLAGS=-L${libomp_dir}/lib
          echo $LDFLAGS
          #   change back to where we started
          cd ${tmp_dir}

      - name: install BLAS++
        run: |
          cd ..
          pwd
          ls
          git clone https://bitbucket.org/icl/blaspp.git
          mkdir blaspp-build
          cd blaspp-build
          pwd
          cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=`pwd`/../blaspp-install -Dbuild_tests=OFF ../blaspp
          make -j2 install

      - name: install Random123
        run: |
          cd ..
          pwd
          ls
          git clone https://github.com/DEShawResearch/Random123.git
          cd Random123/
          mkdir -p `pwd`/../Random123-install/include
          cp -rp include/Random123 `pwd`/../Random123-install/include/

      - name: install LAPACK++
        run: |
          cd ..
          git clone https://bitbucket.org/icl/lapackpp.git
          mkdir lapackpp-build
          cd lapackpp-build
          cmake -DCMAKE_BUILD_TYPE=Debug \
              -Dblaspp_DIR=`pwd`/../blaspp-install/lib/blaspp \
              -DCMAKE_INSTALL_PREFIX=`pwd`/../lapackpp-install \
              -DCMAKE_BINARY_DIR=`pwd` \
              -Dbuild_tests=OFF \
              `pwd`/../lapackpp
          make -j2 install

      - name: build RandLAPACK (Release)
        run: |
          cd ..
          mkdir RandLAPACK-build
          cd RandLAPACK-build
          cmake -DCMAKE_BUILD_TYPE=Release \
              -Dblaspp_DIR=`pwd`/../blaspp-install/lib/blaspp \
              -Dlapackpp_DIR=`pwd`/../lapackpp-install/lib/lapackpp \
              -DRandom123_DIR=`pwd`/../random123-install/include/ \
              -DCMAKE_INSTALL_PREFIX=`pwd`/../RandLAPACK-install \
              `pwd`/../RandLAPACK
          make -j2
          ctest --output-on-failure
          make install

      - name: build benchmarks (with OpenMP)
        run: |
          cd ..
          mkdir benchmark-build
          cd benchmark-build
          cmake -DCMAKE_BINARY_DIR=`pwd` \
            -DRandLAPACK_DIR=`pwd`/../RandLAPACK-install/lib/cmake \
            -Dblaspp_DIR=`pwd`/../blaspp-install/lib/blaspp \
            -Dlapackpp_DIR=`pwd`/../lapackpp-install/lib/lapackpp \
            -DRandom123_DIR=`pwd`/../random123-install/include \
            ../RandLAPACK/benchmark
          make
