name: core-linux
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: webfactory/ssh-agent
        uses: webfactory/ssh-agent@v0.5.4
        with:
            ssh-private-key: ${{ secrets.PRIVATE_CLONE_SSH_KEY }}

      - name: configure OS
        run: |
          # os level stuff
          echo `pwd`
          echo `ls`
          set -x
          export DEBIAN_FRONTEND="noninteractive"
          export TZ="America/Los_Angeles"
          sudo apt-get update -qq
          sudo apt-get install -qq -y git-core gcc g++ gfortran cmake subversion automake m4 libgtest-dev libmkl-dev libopenblas-openmp-dev

      - name: install BLAS++
        run: |
          cd ..
          echo `pwd`
          echo `ls`
          git clone https://bitbucket.org/icl/blaspp.git
          mkdir blaspp-build
          cd blaspp-build
          cmake -DCMAKE_BUILD_TYPE=Release \
              -DCMAKE_INSTALL_PREFIX=`pwd`/../blaspp-install \
              -DCMAKE_BINARY_DIR=`pwd` \
              -Dbuild_tests=OFF \
              ../blaspp
          make -j2 install

      - name: install Random123  
        run: |
          cd ..
          git clone https://github.com/DEShawResearch/random123.git
          cd random123/
          make prefix=`pwd`/../random123-install install-include
      
      - name: install RandBLAS
        run: |
          cd ..
          git clone ssh://git@github.com/BallisticLA/RandBLAS.git
          mkdir RandBLAS-build
          cd RandBLAS-build
          cmake -DCMAKE_BUILD_TYPE=Debug \
              -Dblaspp_DIR=`pwd`/../blaspp-install/lib/blaspp \
              -DRandom123_DIR=`pwd`/../random123-install/include \
              -DCMAKE_INSTALL_PREFIX=`pwd`/../RandBLAS-install \
              -DCMAKE_BINARY_DIR=`pwd` \
              ../RandBLAS/
          make -j2 install
          ctest --output-on-failure
          
      - name: install LAPACK++
        run: |
          cd ..
          git clone https://bitbucket.org/icl/lapackpp.git
          mkdir lapackpp-build
          cd lapackpp-build
          cmake -DCMAKE_BUILD_TYPE=Debug \
              -Dblaspp_DIR=`pwd`/../blaspp-install/lib/blaspp \
              -DCMAKE_INSTALL_PREFIX=`pwd`/../lapackpp-install \
              -DCMAKE_BINARY_DIR=`pwd` \
              -Dbuild_tests=no \
              `pwd`/../lapackpp
          make -j2 install

      - name: build RandLAPACK
        run: |
          cd ..
          mkdir RandLAPACK-build
          cd RandLAPACK-build
          cmake -DCMAKE_BUILD_TYPE=Debug \
              -Dblaspp_DIR=`pwd`/../blaspp-install/lib/blaspp \
              -DRandBLAS_DIR=`pwd`/../RandBLAS-install/lib/cmake \
              -Dlapackpp_DIR=`pwd`/../lapackpp-install/lib/lapackpp \
              -DCMAKE_INSTALL_PREFIX=`pwd`/../RandLAPACK-install \
              -DCMAKE_BINARY_DIR=`pwd` \
              `pwd`/../proto_randlapack
          make
          make install
          ctest
