name: core-linux
on:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: webfactory/ssh-agent
        uses: webfactory/ssh-agent@v0.5.4
        with:
            ssh-private-key: ${{ secrets.PRIVATE_CLONE_SSH_KEY }}

      - name: submodule update
        run: |
          git submodule update --init --recursive

      - name: configure OS
        run: |
          # os level stuff
          echo `pwd`
          echo `ls`
          set -x
          export DEBIAN_FRONTEND="noninteractive"
          export TZ="America/Los_Angeles"
          sudo apt-get update -qq
          sudo apt-get install -qq -y git-core gcc g++ gfortran cmake subversion automake m4 libgtest-dev libmkl-dev libopenblas-openmp-dev

      - name: install BLAS++
        run: |
          cd ..
          echo `pwd`
          echo `ls`
          git clone https://bitbucket.org/icl/blaspp.git
          mkdir blaspp-build
          cd blaspp-build
          cmake -DCMAKE_BUILD_TYPE=Release \
              -DCMAKE_INSTALL_PREFIX=`pwd`/../blaspp-install \
              -DCMAKE_BINARY_DIR=`pwd` \
              -Dbuild_tests=OFF \
              ../blaspp
          make -j2 install

      - name: install Random123
        run: |
          cd ..
          git clone https://github.com/DEShawResearch/random123.git
          cd random123/
          make prefix=`pwd`/../random123-install install-include

      - name: install LAPACK++
        run: |
          cd ..
          git clone https://bitbucket.org/icl/lapackpp.git
          mkdir lapackpp-build
          cd lapackpp-build
          cmake -DCMAKE_BUILD_TYPE=Debug \
              -Dblaspp_DIR=`pwd`/../blaspp-install/lib/blaspp \
              -DCMAKE_INSTALL_PREFIX=`pwd`/../lapackpp-install \
              -DCMAKE_BINARY_DIR=`pwd` \
              -Dbuild_tests=OFF \
              `pwd`/../lapackpp
          make -j2 install

      - name: build and test RandLAPACK (Release)
        run: |
          cd ..
          mkdir RandLAPACK-build
          cd RandLAPACK-build
          cmake -DCMAKE_BUILD_TYPE=Release \
              -Dblaspp_DIR=`pwd`/../blaspp-install/lib/blaspp \
              -Dlapackpp_DIR=`pwd`/../lapackpp-install/lib/lapackpp \
              -DRandom123_DIR=`pwd`/../random123-install/include/ \
              -DCMAKE_INSTALL_PREFIX=`pwd`/../RandLAPACK-install \
              `pwd`/../RandLAPACK
          make -j2
          make -j2 install
          ctest --output-on-failure

      - name: build and test RandLAPACK (Debug/asan)
        run: |
          cd ..
          mkdir RandLAPACK-build-asan
          cd RandLAPACK-build-asan
          cmake -DCMAKE_BUILD_TYPE=Debug \
              -DSANITIZE_ADDRESS=ON \
              -Dblaspp_DIR=`pwd`/../blaspp-install/lib/blaspp \
              -Dlapackpp_DIR=`pwd`/../lapackpp-install/lib/lapackpp \
              -DRandom123_DIR=`pwd`/../random123-install/include/ \
              -DCMAKE_INSTALL_PREFIX=`pwd`/../RandLAPACK-install-asan \
              `pwd`/../RandLAPACK
          make -j2
          make -j2 install
          ctest --output-on-failure
